[build]
  command = "npm run build"
  publish = "out"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_ENV = "production"
  NEXT_PUBLIC_SITE_URL = "https://trendiingz.com"

[functions]
  # Increase function timeout for potential slow operations
  node_bundler = "esbuild"
  included_files = ["content/**/*"]
  external_node_modules = ["gray-matter"]

[dev]
  # Settings for netlify dev
  functions = "netlify/functions"
  publish = "out"

# Redirect API calls to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optimize asset caching
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 